version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  app:
    build: .
    volumes:
      - .:/app/
    ports:
      - "8083:8083"
    depends_on:
      - mysql
#     volumes:
#       - datastore:/go/pkg

# volumes:
#   datastore:
